// Formulario de contacto. Título y bajada: reference/seo-metadata.json.
// Textos del formulario: los de la versión anterior del sitio (ES y EN).
export const copy = {
  es: {
    title: 'Agenda una demo de Relvo',
    lede: 'Cuéntanos cómo cobras hoy y te mostramos Relvo funcionando con un caso como el tuyo: planes recurrentes, contratos o cobro por uso.',
    name: 'Nombre',
    namePlaceholder: 'Tu nombre',
    email: 'Email corporativo',
    emailPlaceholder: 'nombre@empresa.com',
    company: 'Empresa',
    companyPlaceholder: 'Nombre de tu empresa',
    role: 'Cargo',
    rolePlaceholder: 'Selecciona...',
    roleOptions: ['CFO / Director Financiero', 'Gerente Financiero', 'Founder / CEO', 'RevOps', 'Otro'],
    problem: '¿Qué problema quieres resolver?',
    problemOptional: '(opcional)',
    problemPlaceholder: 'Cuéntanos brevemente tu situación actual...',
    submit: 'Enviar',
    sending: 'Enviando...',
    retry: 'Reintentar',
    required: 'Campo requerido',
    invalidEmail: 'Email inválido',
    error: 'Hubo un error al enviar. Intenta de nuevo o escríbenos a contacto@relvoerp.com.',
    successTitle: '¡Listo! Te contactamos pronto.',
    successBody: 'Revisamos tu solicitud y te escribimos en menos de 24 horas.',
  },
  en: {
    title: 'Book a Relvo demo',
    lede: "Tell us how you bill today and we'll show you Relvo working on a case like yours: recurring plans, contracts or usage-based billing.",
    name: 'Name',
    namePlaceholder: 'Your name',
    email: 'Work email',
    emailPlaceholder: 'name@company.com',
    company: 'Company',
    companyPlaceholder: 'Your company name',
    role: 'Role',
    rolePlaceholder: 'Select...',
    roleOptions: ['CFO / Finance Director', 'Finance Manager', 'Founder / CEO', 'RevOps', 'Other'],
    problem: 'What problem are you trying to solve?',
    problemOptional: '(optional)',
    problemPlaceholder: 'Briefly tell us about your current setup...',
    submit: 'Submit',
    sending: 'Sending...',
    retry: 'Retry',
    required: 'Required field',
    invalidEmail: 'Invalid email',
    error: 'Something went wrong. Try again or write to contacto@relvoerp.com.',
    successTitle: "Done! We'll be in touch soon.",
    successBody: 'We review your request and write back within 24 hours.',
  },
}
