// Copy de la home. ES: brief "Web 3.0" 7.3 y mockup aprobado, sin reescribir.
// EN: traducción del ES (aprobada por Ricardo, 2026-10-02).
// Los datos de los visuales son de ejemplo, con nombres ficticios.
export const copy = {
  es: {
    example: 'EJEMPLO',
    hero: {
      eyebrow: 'Revenue Engine para SaaS e IA',
      title: 'Tu pricing, convertido en ingresos. Exacto y sin trabajo manual.',
      subtitle: 'Monetiza tu SaaS o producto de IA como quieras: self-serve con tarjeta o contratos negociados, plan fijo, seats, uso o resultados. Relvo calcula, factura, cobra y concilia en un solo sistema. Agentes de IA sobre rieles determinísticos.',
      demo: 'Agendar demo',
      how: 'Ver cómo funciona',
      logos: 'Operan su revenue con Relvo',
      // Composición de 4 piezas del prototipo: contrato → factura → pago conciliado → MRR
      stage: {
        contract: { title: 'Contrato Nimbo AI', meta: 'Octubre', plan: 'Plan Growth, fijo', planAmount: 'USD 500', usage: '1,2 M llamadas a la API', usageAmount: 'USD 2.400', total: 'Total del período', totalAmount: 'USD 2.900' },
        invoice: { title: 'Factura F-1042', chip: 'Emitida', po: 'OC 4500-221', poState: 'Asociada', sent: 'Enviada a finanzas@nimbo.ai', sentState: 'Hoy' },
        paid: { sender: 'Agente de Relvo, hace un momento', title: 'Pago recibido y conciliado.', context: 'Nimbo AI pagó octubre por transferencia.', amount: 'USD 2.900', running: 'Conciliando', done: 'Conciliado' },
        mrr: { label: 'MRR de octubre', amount: 'USD 187.200', delta: '+USD 2.900' },
      },
    },
    layers: {
      title: 'Tres capas, un solo motor.',
      soft: 'Rieles exactos para calcular, agentes para operar e inteligencia para decidir.',
      numberLocale: 'es-CL',
      rails: {
        title: 'Rieles',
        sub: 'Calculan el monto exacto de cada período.',
        plan: 'Plan Growth, fijo',
        usage: 'Consumo de la API',
        detail: '1,2 M de llamadas a USD 0,002',
        total: 'Total octubre',
      },
      agents: {
        title: 'Agentes',
        sub: 'Hacen el trabajo manual alrededor del cobro.',
        sender: 'Agente de Relvo',
        event: 'Orden de compra asociada.',
        context: 'La OC 4500-221 de Nimbo AI calza con el contrato. La factura sale hoy.',
        running: 'Leyendo la OC',
        done: 'Listo',
      },
      intel: {
        title: 'Inteligencia',
        sub: 'Muestra cómo se mueve tu revenue.',
        label: 'MRR de octubre',
        delta: '+USD 2.900 de Nimbo AI',
      },
    },
    rails: {
      title: 'El cálculo no se negocia.',
      soft: 'Relvo convierte tu pricing en reglas exactas, venga de tu página de precios o de un contrato negociado.',
      tablist: 'Qué hacen los rieles',
      tabs: [
        { title: 'Pricing', desc: 'Del plan fijo al pricing por uso, sin cambiar de sistema.' },
        { title: 'Aprobaciones', desc: 'Órdenes de compra y aprobaciones antes de emitir, cuando tu cliente las exige.' },
        { title: 'Facturación compleja', desc: 'Facturas divididas, prorrateos y glosas a la medida de cada cliente.' },
        { title: 'Cobro y conciliación', desc: 'Cobranza por correo o automática con tarjeta, link de pago o transferencia, conciliada contra el banco.' },
      ],
      pricing: {
        title: 'Contrato Nimbo AI', meta: 'Octubre 2026',
        rows: [
          { label: 'Plan Growth, fijo', amount: 'USD 500' },
          { label: 'Seats adicionales', detail: '12 × USD 20', amount: 'USD 240' },
          { label: 'Consumo de la API', detail: '1,2 M de llamadas, tramo 2 a USD 0,002', amount: 'USD 2.400', exact: true },
          { label: 'Descuento de lanzamiento', detail: 'Fase 1 de 3: 10% sobre el plan fijo', amount: '−USD 50' },
        ],
        total: { label: 'Total del período', amount: 'USD 3.090' },
        chips: ['Facturación mensual', 'Fase 1 de 3'],
      },
      approvals: {
        title: 'Pre-factura de octubre', meta: 'Nimbo AI', done: 'Listo', running: 'En curso',
        steps: [
          { label: 'Pre-factura generada', detail: 'USD 3.090, según contrato', done: true },
          { label: 'OC 4500-221 asociada', detail: 'Monto y vigencia calzan con el contrato', done: true },
          { label: 'Aprobada por el cliente', detail: 'Finanzas de Nimbo AI, 2 de octubre', done: true },
          { label: 'Emisión', detail: 'Programada para hoy', done: false },
        ],
      },
      split: {
        title: 'Factura dividida', meta: 'Total USD 3.090',
        entities: [
          { name: 'Nimbo AI SpA, Chile', share: '60% del contrato', amount: 'USD 1.854' },
          { name: 'Nimbo AI, México', share: '40% del contrato', amount: 'USD 1.236' },
        ],
        glosaLabel: 'Glosa configurada por el cliente',
        glosa: 'Servicio Relvo, octubre 2026. OC 4500-221. Centro de costo: Operaciones.',
        chips: ['Prorrateo: 5 seats desde el 16 de octubre'],
      },
      collection: {
        title: 'Factura F-1042', meta: 'Vence el 30 de octubre',
        rows: [
          { label: 'Monto facturado', amount: 'USD 3.090' },
          { label: 'Pago recibido', detail: 'Transferencia, 18 de octubre. Conciliado con el banco', amount: '−USD 2.000' },
        ],
        balance: { label: 'Saldo pendiente', amount: 'USD 1.090' },
        status: 'Pago parcial conciliado',
        chips: ['Recordatorio por correo el 25 de octubre'],
      },
    },
    agents: {
      title: 'El trabajo manual que se come tu mes, hecho.',
      soft: 'Los agentes leen órdenes de compra, siguen correos y avisan a tu equipo. Cuando algo no calza, te preguntan.',
      feedTitle: 'Actividad de hoy',
      inboxTitle: 'Requiere revisión',
      done: 'Listo',
      running: 'En curso',
      feed: [
        { time: '09:02', text: 'Leyó la OC 4500-221 de Faro Analytics. Monto y vigencia calzan con el contrato.', status: 'done' },
        { time: '09:05', text: 'Asoció la OC a la pre-factura de octubre.', status: 'done' },
        { time: '09:14', text: 'Escribió a finanzas de Nimbo AI para pedir la HES pendiente.', status: 'running' },
        { time: '09:20', text: 'Avisó en #finanzas: 3 facturas listas para emitir.', status: 'done' },
        { time: '09:31', text: 'Respondió vía MCP cuánto factura Tandem SaaS este mes.', status: 'done' },
      ],
      inbox: [
        { title: 'La OC no calza con el contrato.', text: 'Tandem SaaS envió una OC por USD 1.800; el contrato dice USD 2.100.', actions: ['Revisar', 'Pedir nueva OC'] },
        { title: 'Cambio de razón social.', text: 'Faro Analytics pide facturar octubre a otra sociedad del grupo.', actions: ['Revisar', 'Responder'] },
      ],
      principleStrong: 'Tú apruebas las excepciones. Nada sale sin que cuadre.',
      principle: 'Los agentes no calculan montos: eso lo hace el motor, siempre igual.',
    },
    intel: {
      title: 'Qué está pasando con tu revenue.',
      soft: 'Como Relvo opera todo el flujo, de la venta al pago, ve lo que ninguna planilla junta.',
      tablist: 'Reportes',
      also: 'Además: facturación, recaudación, cuentas por cobrar y reconocimiento de ingresos bajo IFRS 15.',
      numberLocale: 'es-CL',
      months: ['Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep'],
      tabs: [
        {
          label: 'Qué usan vs. qué pagan',
          kpis: [{ label: 'Consumo sobre el MRR', value: '21%', note: 'Subió desde 11% en abril. Crece más rápido que el plan fijo.' }],
          chartLabel: 'MRR fijo y consumo por mes, abril a septiembre',
          legend: ['MRR fijo', 'Consumo: llamadas API', 'Consumo: documentos'],
        },
        {
          label: 'Qué tan rápido conviertes trabajo en caja',
          kpis: [
            { label: 'Días en facturar (DTI)', value: '3', note: 'Desde que termina el período hasta que sale la factura.' },
            { label: 'Días en cobrar (DSO)', value: '38', note: '9 días menos que en abril.' },
          ],
          chartLabel: 'DTI y DSO por mes',
          legend: ['DTI', 'DSO'],
        },
        {
          label: 'Cómo se mueve tu MRR',
          kpis: [{ label: 'MRR de octubre', value: '192,4k', note: '+8.100 USD neto respecto a septiembre.' }],
          chartLabel: 'Movimiento del MRR de septiembre a octubre',
          steps: ['Sep', 'Altas', 'Expansión', 'Consumo', 'Contracción', 'Churn', 'Oct'],
        },
      ],
    },
    products: {
      title: 'Todo tu revenue, en un solo sistema.',
      soft: 'Seis productos que funcionan juntos, del pricing al reporte.',
      go: 'Ver',
      layers: { rails: 'Rieles', agents: 'Agentes', intelligence: 'Inteligencia' },
      contratos: { lines: [['Plan fijo', 'USD 500'], ['12 seats', 'USD 240'], ['Consumo por tramos', 'USD 2.400']], total: ['Total', 'USD 3.140'], go: 'Ver Contratos y pricing' },
      medicion: { note: '1,2 M llamadas en octubre', go: 'Ver Medición del consumo' },
      aprobaciones: { lines: [['OC 4500-221', 'Calza', 'ok'], ['OC 4500-198', 'Revisar', 'review']], go: 'Ver Aprobaciones' },
      cxc: { lines: [['F-1042, Nimbo AI', 'Conciliada', 'ok'], ['F-1043, Faro Analytics', 'Pago parcial', 'review'], ['F-1044, Tandem SaaS', 'Enviada', 'plain']], go: 'Ver Cuentas por cobrar' },
      agentes: { lines: [['Leyó la OC 4500-221', 'Listo', 'ok'], ['Pidió la HES pendiente', 'En curso', 'review']], go: 'Ver Agentes' },
      reporteria: { metrics: [['MRR', '192,4k'], ['Consumo', '21%'], ['DSO', '38 días'], ['DTI', '3 días']], go: 'Ver Reportería' },
    },
    bridge: {
      title: 'Cobra como vendes.',
      soft: 'Self-serve con tarjeta o contratos negociados: Relvo opera los dos en el mismo motor, con las mismas reglas y los mismos reportes.',
      plans: {
        title: 'Planes recurrentes',
        body: 'Tus clientes pagan con tarjeta. Relvo mide el consumo, cobra el plan y el uso en automático y te muestra cómo se mueve tu MRR.',
        cta: 'Ver precios',
        link: 'Cómo funciona para planes recurrentes',
      },
      contracts: {
        title: 'Contratos con pricing híbrido',
        body: 'Tus clientes firman contratos. Relvo convierte cada condición en reglas, gestiona las órdenes de compra, factura y cobra.',
        cta: 'Agendar demo',
        link: 'Cómo funciona para contratos',
      },
      usageQuestion: '¿Empezando a cobrar por uso?',
      usageLink: 'Suma consumo sin cambiar de sistema',
    },
    case: {
      title: 'Lo que cambió para nuestros clientes.',
      company: 'TGP',
      about: 'Agencia de prospecting. Cobra un fee fijo más un variable cada mes.',
      big: '70%',
      bigLabel: 'menos tiempo operativo',
      bigSub: 'mientras su operación creció 30% en 3 meses.',
      metricStrong: 'Días en facturar (DTI)',
      metric: ', con aprobaciones de clientes y órdenes de compra incluidas.',
      before: 'Antes',
      after: 'Con Relvo',
      days: 'días',
      quote: 'Hoy trabajamos mucho más rápido, con mayor confianza en los cálculos y con un proceso que puede escalar junto a nuestro crecimiento.',
      author: 'Francesco Cotroneo',
      role: 'Operations Lead, TGP',
    },
    latam: {
      title: 'Hecho para cobrar en LatAm.',
      soft: 'Un solo sistema conectado a los bancos, medios de pago y facturación electrónica de la región.',
      points: [
        'Facturación electrónica en Chile y México, emitida desde el mismo sistema.',
        'Conciliación con bancos locales.',
        'Cobro con Toku, Fintoc y Stripe.',
        'Cualquier moneda, con conversión automática, incluida la UF.',
        'Varias sociedades en un solo cierre.',
        'Órdenes de compra y aprobaciones, como compran las empresas en la región.',
      ],
    },
    integrations: {
      title: 'Se conecta a lo que ya usas.',
      soft: 'Tu CRM, tu ERP, tus medios de pago y tu banco, conectados a un solo motor.',
      layers: ['01 Rieles', '02 Agentes', '03 Inteligencia'],
      inputs: [
        { name: 'HubSpot', flow: 'Ventas' },
        { name: 'Tu producto', flow: 'Consumo vía API' },
        { name: 'Self-serve', flow: 'Checkout con tarjeta' },
      ],
      collection: { kind: 'Cobro', name: 'Stripe · Toku · Fintoc', out: 'Cobros', back: 'Pagos' },
      bank: { kind: 'Banco', name: 'Fintoc', back: 'Movimientos para conciliar' },
      outputs: [
        { kind: 'Facturación electrónica', name: 'Chile y México', flow: 'Facturas' },
        { kind: 'ERP', name: 'Sintropix', flow: null },
        { kind: 'Equipo', name: 'Slack · Google Chat', flow: 'Avisos y excepciones' },
        { kind: null, name: 'Tus herramientas de IA', flow: 'MCP' },
      ],
    },

    cta: {
      title: 'Tú vendes. Relvo hace el resto.',
      demo: 'Agendar demo',
    },
  },
  // EN: las claves nuevas o cambiadas del prototipo quedan marcadas como pendientes (no se traducen
  // todavía). Mientras tanto la home en inglés es una página pendiente: no se publica en producción.
  en: {
    example: 'EXAMPLE',
    hero: {
      eyebrow: 'Revenue Engine for SaaS and AI',
      title: 'Your pricing, turned into revenue. Exact, with no manual work.',
      subtitle: 'Monetize your SaaS or AI product however you want: self-serve by card or negotiated contracts, fixed plans, seats, usage or outcomes. Relvo calculates, invoices, collects and reconciles in one system. AI agents on deterministic rails.',
      demo: 'Book a demo',
      how: 'See how it works',
      logos: 'They run their revenue on Relvo',
      stage: {
        contract: { title: '[PENDIENTE]', meta: '[PENDIENTE]', plan: '[PENDIENTE]', planAmount: '[PENDIENTE]', usage: '[PENDIENTE]', usageAmount: '[PENDIENTE]', total: '[PENDIENTE]', totalAmount: '[PENDIENTE]' },
        invoice: { title: '[PENDIENTE]', chip: '[PENDIENTE]', po: '[PENDIENTE]', poState: '[PENDIENTE]', sent: '[PENDIENTE]', sentState: '[PENDIENTE]' },
        paid: { sender: '[PENDIENTE]', title: '[PENDIENTE]', context: '[PENDIENTE]', amount: '[PENDIENTE]', running: '[PENDIENTE]', done: '[PENDIENTE]' },
        mrr: { label: '[PENDIENTE]', amount: '[PENDIENTE]', delta: '[PENDIENTE]' },
      },
    },
    layers: {
      title: '[PENDIENTE]',
      soft: '[PENDIENTE]',
      numberLocale: 'en-US',
      rails: {
        title: 'Rails',
        sub: 'They calculate the exact amount for every period.',
        plan: 'Growth plan, fixed',
        usage: 'API usage',
        detail: '1.2 M calls at USD 0.002',
        total: 'October total',
      },
      agents: {
        title: 'Agents',
        sub: 'They do the manual work around billing.',
        sender: 'Relvo agent',
        event: 'Purchase order matched.',
        context: 'PO 4500-221 from Nimbo AI matches the contract. The invoice goes out today.',
        running: 'Reading the PO',
        done: 'Done',
      },
      intel: {
        title: 'Intelligence',
        sub: 'It shows how your revenue is moving.',
        label: 'October MRR',
        delta: '+USD 2,900 from Nimbo AI',
      },
    },
    rails: {
      title: 'The calculation is not up for negotiation.',
      soft: '[PENDIENTE]',
      tablist: '[PENDIENTE]',
      tabs: [{ title: '[PENDIENTE]', desc: '[PENDIENTE]' }, { title: '[PENDIENTE]', desc: '[PENDIENTE]' }, { title: '[PENDIENTE]', desc: '[PENDIENTE]' }, { title: '[PENDIENTE]', desc: '[PENDIENTE]' }],
      pricing: {
        title: '[PENDIENTE]', meta: '[PENDIENTE]',
        rows: [{ label: '[PENDIENTE]', amount: '[PENDIENTE]' }, { label: '[PENDIENTE]', detail: '[PENDIENTE]', amount: '[PENDIENTE]' }, { label: '[PENDIENTE]', detail: '[PENDIENTE]', amount: '[PENDIENTE]', exact: true }, { label: '[PENDIENTE]', detail: '[PENDIENTE]', amount: '[PENDIENTE]' }],
        total: { label: '[PENDIENTE]', amount: '[PENDIENTE]' },
        chips: ['[PENDIENTE]', '[PENDIENTE]'],
      },
      approvals: {
        title: '[PENDIENTE]', meta: '[PENDIENTE]', done: '[PENDIENTE]', running: '[PENDIENTE]',
        steps: [{ label: '[PENDIENTE]', detail: '[PENDIENTE]', done: true }, { label: '[PENDIENTE]', detail: '[PENDIENTE]', done: true }, { label: '[PENDIENTE]', detail: '[PENDIENTE]', done: true }, { label: '[PENDIENTE]', detail: '[PENDIENTE]', done: false }],
      },
      split: {
        title: '[PENDIENTE]', meta: '[PENDIENTE]',
        entities: [{ name: '[PENDIENTE]', share: '[PENDIENTE]', amount: '[PENDIENTE]' }, { name: '[PENDIENTE]', share: '[PENDIENTE]', amount: '[PENDIENTE]' }],
        glosaLabel: '[PENDIENTE]', glosa: '[PENDIENTE]',
        chips: ['[PENDIENTE]'],
      },
      collection: {
        title: '[PENDIENTE]', meta: '[PENDIENTE]',
        rows: [{ label: '[PENDIENTE]', amount: '[PENDIENTE]' }, { label: '[PENDIENTE]', detail: '[PENDIENTE]', amount: '[PENDIENTE]' }],
        balance: { label: '[PENDIENTE]', amount: '[PENDIENTE]' },
        status: '[PENDIENTE]',
        chips: ['[PENDIENTE]'],
      },
    },
    agents: {
      title: 'The manual work that eats your month, done.',
      soft: '[PENDIENTE]',
      feedTitle: '[PENDIENTE]',
      inboxTitle: '[PENDIENTE]',
      done: '[PENDIENTE]',
      running: '[PENDIENTE]',
      feed: [{ time: '09:02', text: '[PENDIENTE]', status: 'done' }, { time: '09:05', text: '[PENDIENTE]', status: 'done' }, { time: '09:14', text: '[PENDIENTE]', status: 'running' }, { time: '09:20', text: '[PENDIENTE]', status: 'done' }, { time: '09:31', text: '[PENDIENTE]', status: 'done' }],
      inbox: [{ title: '[PENDIENTE]', text: '[PENDIENTE]', actions: ['[PENDIENTE]', '[PENDIENTE]'] }, { title: '[PENDIENTE]', text: '[PENDIENTE]', actions: ['[PENDIENTE]', '[PENDIENTE]'] }],
      principleStrong: '[PENDIENTE]',
      principle: '[PENDIENTE]',
    },
    intel: {
      title: 'What is happening with your revenue.',
      soft: 'Because Relvo runs the whole flow, from sale to payment, it sees what no spreadsheet puts together.',
      tablist: '[PENDIENTE]',
      also: 'Also: invoicing, collections, accounts receivable and revenue recognition under IFRS 15.',
      numberLocale: 'en-US',
      months: ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'],
      tabs: [
        { label: 'What they use vs. what they pay', kpis: [{ label: '[PENDIENTE]', value: '21%', note: '[PENDIENTE]' }], chartLabel: '[PENDIENTE]', legend: ['[PENDIENTE]', '[PENDIENTE]', '[PENDIENTE]'] },
        { label: 'How fast you turn work into cash', kpis: [{ label: '[PENDIENTE]', value: '3', note: '[PENDIENTE]' }, { label: '[PENDIENTE]', value: '38', note: '[PENDIENTE]' }], chartLabel: '[PENDIENTE]', legend: ['DTI', 'DSO'] },
        { label: 'How your MRR moves', kpis: [{ label: '[PENDIENTE]', value: '192.4k', note: '[PENDIENTE]' }], chartLabel: '[PENDIENTE]', steps: ['Sep', '[PENDIENTE]', '[PENDIENTE]', '[PENDIENTE]', '[PENDIENTE]', 'Churn', 'Oct'] },
      ],
    },
    products: {
      title: '[PENDIENTE]',
      soft: '[PENDIENTE]',
      go: '[PENDIENTE]',
      layers: { rails: 'Rails', agents: 'Agents', intelligence: 'Intelligence' },
      contratos: { lines: [['[PENDIENTE]', 'USD 500'], ['[PENDIENTE]', 'USD 240'], ['[PENDIENTE]', 'USD 2,400']], total: ['Total', 'USD 3,140'], go: '[PENDIENTE]' },
      medicion: { note: '[PENDIENTE]', go: '[PENDIENTE]' },
      aprobaciones: { lines: [['PO 4500-221', '[PENDIENTE]', 'ok'], ['PO 4500-198', '[PENDIENTE]', 'review']], go: '[PENDIENTE]' },
      cxc: { lines: [['[PENDIENTE]', '[PENDIENTE]', 'ok'], ['[PENDIENTE]', '[PENDIENTE]', 'review'], ['[PENDIENTE]', '[PENDIENTE]', 'plain']], go: '[PENDIENTE]' },
      agentes: { lines: [['[PENDIENTE]', '[PENDIENTE]', 'ok'], ['[PENDIENTE]', '[PENDIENTE]', 'review']], go: '[PENDIENTE]' },
      reporteria: { metrics: [['MRR', '192.4k'], ['[PENDIENTE]', '21%'], ['DSO', '[PENDIENTE]'], ['DTI', '[PENDIENTE]']], go: '[PENDIENTE]' },
    },
    bridge: {
      title: 'Bill the way you sell.',
      soft: '[PENDIENTE]',
      plans: { title: 'Recurring plans', body: '[PENDIENTE]', cta: '[PENDIENTE]', link: '[PENDIENTE]' },
      contracts: { title: 'Hybrid pricing contracts', body: '[PENDIENTE]', cta: 'Book a demo', link: '[PENDIENTE]' },
      usageQuestion: '[PENDIENTE]',
      usageLink: '[PENDIENTE]',
    },
    case: {
      title: 'What changed for our customers.',
      company: 'TGP',
      about: '[PENDIENTE]',
      big: '70%',
      bigLabel: '[PENDIENTE]',
      bigSub: '[PENDIENTE]',
      metricStrong: '[PENDIENTE]',
      metric: '[PENDIENTE]',
      before: '[PENDIENTE]',
      after: '[PENDIENTE]',
      days: '[PENDIENTE]',
      quote: '[PENDIENTE]',
      author: 'Francesco Cotroneo',
      role: 'Operations Lead, TGP',
    },
    latam: {
      title: 'Built to get paid in LatAm.',
      soft: '[PENDIENTE]',
      points: [
        'E-invoicing in Chile and Mexico, issued from the same system.',
        'Reconciliation with local banks.',
        'Collection with Toku, Fintoc and Stripe.',
        'Any currency, with automatic conversion, including the UF.',
        'Multiple legal entities in a single close.',
        'Purchase orders and approvals, the way companies in the region buy.',
      ],
    },
    integrations: {
      title: 'It connects to what you already use.',
      soft: '[PENDIENTE]',
      layers: ['01 Rails', '02 Agents', '03 Intelligence'],
      inputs: [
        { name: 'HubSpot', flow: 'Sales' },
        { name: 'Your product', flow: 'Usage via API' },
        { name: 'Self-serve', flow: 'Card checkout' },
      ],
      collection: { kind: 'Collection', name: 'Stripe · Toku · Fintoc', out: 'Charges', back: 'Payments' },
      bank: { kind: 'Bank', name: 'Fintoc', back: 'Transactions to reconcile' },
      outputs: [
        { kind: 'E-invoicing', name: 'Chile and Mexico', flow: 'Invoices' },
        { kind: 'ERP', name: 'Sintropix', flow: null },
        { kind: 'Team', name: 'Slack · Google Chat', flow: 'Alerts and exceptions' },
        { kind: null, name: 'Your AI tools', flow: 'MCP' },
      ],
    },

    cta: {
      title: 'You sell. Relvo does the rest.',
      demo: 'Book a demo',
    },
  },
}
