// Copy de la home. ES: brief "Web 3.0" 7.3 y mockup aprobado, sin reescribir.
// EN: traducción del ES (aprobada por Ricardo, 2026-10-02).
// Los datos de los visuales son de ejemplo, con nombres ficticios.
export const copy = {
  es: {
    example: 'EJEMPLO',
    hero: {
      eyebrow: 'Revenue Engine para SaaS e IA',
      title: 'Tu pricing, convertido en ingresos. Exacto y sin trabajo manual.',
      subtitle: 'Monetiza tu SaaS o producto de IA como quieras: self-serve con tarjeta o contratos negociados, plan fijo, seats, uso o resultados. Relvo calcula, factura, cobra y concilia en un solo sistema. Agentes de IA sobre rieles determinísticos.',
      demo: 'Agendar demo',
      how: 'Ver cómo funciona',
      logos: 'Operan su revenue con Relvo',
      card: {
        sender: 'Agente de Relvo, hace un momento',
        title: 'Factura enviada y conciliada.',
        context: 'Nimbo AI pagó septiembre: plan fijo más 1,2 millones de llamadas a la API.',
        amount: 'USD 12.400',
        chip: 'Cobrado',
      },
    },
    layers: {
      title: 'Tres capas, un solo motor',
      lede: 'Rieles exactos para calcular, agentes para operar e inteligencia para decidir. Cada capa se apoya en la anterior.',
      numberLocale: 'es-CL',
      rails: {
        title: 'Rieles',
        sub: 'Calculan el monto exacto de cada período.',
        plan: 'Plan Growth, fijo',
        usage: 'Consumo de la API',
        detail: '1,2 M de llamadas a USD 0,002',
        total: 'Total octubre',
      },
      agents: {
        title: 'Agentes',
        sub: 'Hacen el trabajo manual alrededor del cobro.',
        sender: 'Agente de Relvo',
        event: 'Orden de compra asociada.',
        context: 'La OC 4500-221 de Nimbo AI calza con el contrato. La factura sale hoy.',
        running: 'Leyendo la OC',
        done: 'Listo',
      },
      intel: {
        title: 'Inteligencia',
        sub: 'Muestra cómo se mueve tu revenue.',
        label: 'MRR de octubre',
        delta: '+USD 2.900 de Nimbo AI',
      },
    },
    rails: {
      title: 'El cálculo no se negocia.',
      lede: 'Relvo convierte tu pricing en reglas: planes, seats, uso, fases, descuentos y reajustes, venga de tu página de precios o de un contrato negociado. Mismo plan y mismo consumo, siempre el mismo monto.',
      points: [
        'Del plan fijo al pricing por uso, sin cambiar de sistema.',
        'Aprobaciones y órdenes de compra antes de emitir, cuando tu cliente las exige.',
        'Facturas divididas, prorrateos y glosas a la medida de cada cliente.',
        'Cobra con mensajes de cobranza o en automático con tarjeta, link de pago o transferencia, y concilia contra el banco, incluso pagos parciales.',
      ],
      pendingVisual: 'Regla de pricing de un contrato, total bajo doble filete',
    },
    agents: {
      title: 'El trabajo manual que se come tu mes, hecho.',
      lede: 'Los agentes leen las órdenes de compra, siguen los correos hasta conseguir lo que falta y avisan a tu equipo en Slack o Google Chat. Cuando algo no calza, se detienen y te preguntan.',
      punch: 'Tú apruebas las excepciones. Nada sale sin que cuadre.',
      card: {
        sender: 'Agente de Relvo, hace 2 minutos',
        title: 'Orden de compra leída.',
        context: 'La OC 4500-221 de Faro Analytics calza con el contrato. La factura queda lista para emitir.',
        chip: 'Listo',
      },
    },
    intel: {
      title: 'Qué está pasando con tu revenue.',
      lede: 'Como Relvo opera todo el flujo, de la venta al pago, ve lo que ninguna planilla junta.',
      support: 'Además: facturación, recaudación, cuentas por cobrar y reconocimiento de ingresos bajo IFRS 15.',
      tabs: [
        { label: 'Qué usan vs. qué pagan', desc: 'MRR vs. consumo por métrica. Quién usa más de lo que paga y quién está en riesgo.', pendingVisual: 'Gráfico: MRR vs. consumo por métrica' },
        { label: 'Qué tan rápido conviertes trabajo en caja', desc: 'Días en facturar (DTI) y días en cobrar (DSO), lado a lado.', pendingVisual: 'Gráfico: DTI y DSO lado a lado' },
        { label: 'Cómo se mueve tu MRR', desc: 'Altas, expansión, consumo, contracción y churn, mes a mes.', pendingVisual: 'Gráfico: movimiento de MRR mes a mes' },
      ],
    },
    bridge: {
      title: 'Cobra como vendes.',
      lede: 'Self-serve con tarjeta o contratos negociados: la mayoría de los SaaS tienen las dos cosas. Relvo las opera en el mismo motor, con las mismas reglas y los mismos reportes.',
      plans: {
        title: 'Planes recurrentes',
        body: 'Tus clientes pagan con tarjeta. Relvo mide el consumo, cobra el plan y el uso en automático y te muestra cómo se mueve tu MRR.',
      },
      contracts: {
        title: 'Contratos con pricing híbrido',
        body: 'Tus clientes firman contratos. Relvo convierte cada condición en reglas, gestiona las órdenes de compra, factura y cobra.',
      },
      demo: 'Agendar demo',
      agencyQuestion: '¿Agencia con fee variable cada mes?',
      agencyLink: 'Mira cómo lo resolvió TGP.',
    },
    latam: {
      title: 'Hecho para cobrar en LatAm.',
      lede: 'Un solo sistema que ya se conecta con los bancos, medios de pago y facturación electrónica de la región.',
      points: [
        'Facturación electrónica en Chile y México, emitida desde el mismo sistema.',
        'Conciliación con bancos locales.',
        'Cobro con Toku, Fintoc y Stripe.',
        'Cualquier moneda, con conversión automática, incluida la UF.',
        'Varias sociedades en un solo cierre.',
        'Órdenes de compra y aprobaciones, como compran las empresas en la región.',
      ],
    },
    integrations: {
      title: 'Se conecta a lo que ya usas.',
      lede: 'Tu CRM, tus medios de pago, tu banco, tu ERP y tu equipo, conectados a un solo motor.',
      label: 'Integraciones de Relvo: HubSpot, Stripe, Toku, Fintoc, Sintropix, Slack, Google Chat y herramientas de IA vía MCP',
    },
    cta: {
      title: 'Tú vendes. Relvo hace el resto.',
      demo: 'Agendar demo',
    },
    pending: {
      optional: 'Sección opcional',
      proofNote: 'Si no hay cifra real al lanzar, se omite.',
      casesNote: 'Tarjeta de caso sin cita. Se omite si no hay cifra real al lanzar.',
      casesTitle: 'Lo que cambió para nuestros clientes.',
      measure: '[PENDIENTE] Qué mide',
      value: '[PENDIENTE]',
      compare: '[PENDIENTE] Contra qué se compara',
      judgement: '[PENDIENTE] Si es buena o mala',
    },
  },
  en: {
    example: 'EXAMPLE',
    hero: {
      eyebrow: 'Revenue Engine for SaaS and AI',
      title: 'Your pricing, turned into revenue. Exact, with no manual work.',
      subtitle: 'Monetize your SaaS or AI product however you want: self-serve by card or negotiated contracts, fixed plans, seats, usage or outcomes. Relvo calculates, invoices, collects and reconciles in one system. AI agents on deterministic rails.',
      demo: 'Book a demo',
      how: 'See how it works',
      logos: 'They run their revenue on Relvo',
      card: {
        sender: 'Relvo agent, just now',
        title: 'Invoice sent and reconciled.',
        context: 'Nimbo AI paid September: fixed plan plus 1.2 million API calls.',
        amount: 'USD 12,400',
        chip: 'Paid',
      },
    },
    layers: {
      title: 'Three layers, one engine',
      lede: 'Exact rails to calculate, agents to operate and intelligence to decide. Each layer builds on the one before.',
      numberLocale: 'en-US',
      rails: {
        title: 'Rails',
        sub: 'They calculate the exact amount for every period.',
        plan: 'Growth plan, fixed',
        usage: 'API usage',
        detail: '1.2 M calls at USD 0.002',
        total: 'October total',
      },
      agents: {
        title: 'Agents',
        sub: 'They do the manual work around billing.',
        sender: 'Relvo agent',
        event: 'Purchase order matched.',
        context: 'PO 4500-221 from Nimbo AI matches the contract. The invoice goes out today.',
        running: 'Reading the PO',
        done: 'Done',
      },
      intel: {
        title: 'Intelligence',
        sub: 'It shows how your revenue is moving.',
        label: 'October MRR',
        delta: '+USD 2,900 from Nimbo AI',
      },
    },
    rails: {
      title: 'The calculation is not up for negotiation.',
      lede: 'Relvo turns your pricing into rules: plans, seats, usage, phases, discounts and price adjustments, whether they come from your pricing page or a negotiated contract. Same plan and same usage, always the same amount.',
      points: [
        'From fixed plans to usage-based pricing, without switching systems.',
        'Approvals and purchase orders before invoicing, when your customer requires them.',
        'Split invoices, proration and line descriptions tailored to each customer.',
        'Collect with collection emails or automatically by card, payment link or bank transfer, and reconcile against the bank, even partial payments.',
      ],
      pendingVisual: 'Pricing rule of a contract, total under a double rule',
    },
    agents: {
      title: 'The manual work that eats your month, done.',
      lede: 'Agents read purchase orders, follow up on emails until they get what is missing and alert your team in Slack or Google Chat. When something does not match, they stop and ask you.',
      punch: 'You approve the exceptions. Nothing goes out until it adds up.',
      card: {
        sender: 'Relvo agent, 2 minutes ago',
        title: 'Purchase order read.',
        context: 'PO 4500-221 from Faro Analytics matches the contract. The invoice is ready to issue.',
        chip: 'Done',
      },
    },
    intel: {
      title: 'What is happening with your revenue.',
      lede: 'Because Relvo runs the whole flow, from sale to payment, it sees what no spreadsheet puts together.',
      support: 'Also: invoicing, collections, accounts receivable and revenue recognition under IFRS 15.',
      tabs: [
        { label: 'What they use vs. what they pay', desc: 'MRR vs. usage by metric. Who uses more than they pay for and who is at risk.', pendingVisual: 'Chart: MRR vs. usage by metric' },
        { label: 'How fast you turn work into cash', desc: 'Days to invoice (DTI) and days to collect (DSO), side by side.', pendingVisual: 'Chart: DTI and DSO side by side' },
        { label: 'How your MRR moves', desc: 'New, expansion, usage, contraction and churn, month by month.', pendingVisual: 'Chart: MRR movement month by month' },
      ],
    },
    bridge: {
      title: 'Bill the way you sell.',
      lede: 'Self-serve by card or negotiated contracts: most SaaS companies have both. Relvo runs them on the same engine, with the same rules and the same reports.',
      plans: {
        title: 'Recurring plans',
        body: 'Your customers pay by card. Relvo meters usage, collects the plan and the usage automatically and shows you how your MRR moves.',
      },
      contracts: {
        title: 'Hybrid pricing contracts',
        body: 'Your customers sign contracts. Relvo turns every term into rules, handles purchase orders, invoices and collects.',
      },
      demo: 'Book a demo',
      agencyQuestion: 'Agency with a variable fee every month?',
      agencyLink: 'See how TGP solved it.',
    },
    latam: {
      title: 'Built to get paid in LatAm.',
      lede: 'One system already connected to the banks, payment methods and e-invoicing of the region.',
      points: [
        'E-invoicing in Chile and Mexico, issued from the same system.',
        'Reconciliation with local banks.',
        'Collection with Toku, Fintoc and Stripe.',
        'Any currency, with automatic conversion, including the UF.',
        'Multiple legal entities in a single close.',
        'Purchase orders and approvals, the way companies in the region buy.',
      ],
    },
    integrations: {
      title: 'It connects to what you already use.',
      lede: 'Your CRM, your payment methods, your bank, your ERP and your team, connected to one engine.',
      label: 'Relvo integrations: HubSpot, Stripe, Toku, Fintoc, Sintropix, Slack, Google Chat and AI tools via MCP',
    },
    cta: {
      title: 'You sell. Relvo does the rest.',
      demo: 'Book a demo',
    },
    pending: {
      optional: 'Optional section',
      proofNote: 'Omitted if there is no real figure at launch.',
      casesNote: 'Case card without a quote. Omitted if there is no real figure at launch.',
      casesTitle: 'What changed for our customers.',
      measure: '[PENDING] What it measures',
      value: '[PENDING]',
      compare: '[PENDING] What it is compared against',
      judgement: '[PENDING] Whether it is good or bad',
    },
  },
}
