// Copy de la home. ES: brief "Web 3.0" 7.3 y mockup aprobado, sin reescribir.
// EN: traducción del ES (aprobada por Ricardo, 2026-10-02).
// Los datos de los visuales son de ejemplo, con nombres ficticios.
export const copy = {
  es: {
    example: 'EJEMPLO',
    hero: {
      eyebrow: 'Revenue Engine para SaaS e IA',
      title: 'Tu pricing, convertido en ingresos. Exacto y sin trabajo manual.',
      subtitle: 'Plan fijo, seats, uso o resultados, con tarjeta o con contrato. Relvo calcula, factura, cobra y concilia cada peso en un solo sistema.',
      demo: 'Agendar demo',
      how: 'Ver cómo funciona',
      logos: 'Operan su revenue con Relvo',
      // Composición del prototipo v2: ventana de la app → tokens → factura → pago conciliado
      stage: {
        window: {
          url: 'app.getrelvo.ai/contratos/nimbo-ai', brand: 'Relvo', nav: ['Contratos', 'Facturas', 'Cobranza', 'Reportes'],
          label: 'Contrato', name: 'Nimbo AI', status: 'Activo',
          columns: ['Factura', 'Monto', 'Estado'],
          rows: [['F-1042', 'USD 2.900', 'Emitida'], ['F-1031', 'USD 2.760', 'Pagada']],
          paid: 'Pagada',
        },
        usage: { title: 'Tokens', price: 'USD 0,002 por 1.000', amount: '1.200 M', of: 'de 1.500 M', period: 'Últimos 30 días' },
        invoice: { title: 'Factura F-1042', meta: 'Octubre', total: 'USD 2.900', rows: [['Plan Growth, fijo', '500'], ['1.200 M tokens', '2.400']], totalLabel: 'Total' },
        toast: { title: 'Pago conciliado', meta: 'Nimbo AI, hace un momento' },
      },
    },
    layers: {
      title: 'Tres capas, un solo motor.',
      soft: 'Rieles para calcular, agentes para operar, inteligencia para decidir.',
      numberLocale: 'es-CL',
      rails: {
        title: 'Rieles',
        sub: 'Calculan el monto exacto de cada período.',
        plan: 'Plan Growth, fijo',
        usage: 'Consumo de tokens',
        detail: '1.200 M tokens a USD 0,002 por 1.000',
        total: 'Total octubre',
      },
      agents: {
        title: 'Agentes',
        sub: 'Hacen el trabajo manual alrededor del cobro.',
        sender: 'Agente de Relvo',
        event: 'Orden de compra asociada.',
        context: 'La OC 4500-221 de Nimbo AI calza con el contrato. La factura sale hoy.',
        running: 'Leyendo la OC',
        done: 'Listo',
      },
      intel: {
        title: 'Inteligencia',
        sub: 'Muestra cómo se mueve tu revenue.',
        label: 'MRR de octubre',
        delta: '+USD 2.900 de Nimbo AI',
      },
    },
    manifesto: {
      label: 'Principio de Relvo',
      lines: ['La IA no calcula tu plata.', 'El motor sí.'],
    },
    rails: {
      title: 'El cálculo no se negocia.',
      soft: 'Tu pricing, convertido en reglas exactas.',
      tablist: 'Qué hacen los rieles',
      tabs: [
        { title: 'Pricing', desc: 'Del plan fijo al pricing por uso.' },
        { title: 'Aprobaciones', desc: 'Cada factura con su OC aprobada.' },
        { title: 'Facturación compleja', desc: 'Divididas, prorrateadas y con tu glosa.' },
        { title: 'Cobro y conciliación', desc: 'Cada pago, cuadrado contra su factura.' },
      ],
      pricing: {
        mark: 'N', plan: 'Plan Growth', meta: 'Nimbo AI, facturación mensual', price: 'USD 500', per: '/mes',
        seats: ['Seats adicionales', '12 × USD 20'],
        tokens: ['Tokens', '1.200 M'],
        tiers: ['Tramo 1, incluido', 'Tramo 2'],
        discount: ['Descuento de lanzamiento', 'Fase 1 de 3'],
        total: ['Total octubre', 'USD 3.090'],
      },
      approvals: {
        title: 'Factura de octubre', meta: 'Nimbo AI',
        steps: [
          { label: 'Pre-factura generada', detail: '1 de octubre', done: true },
          { label: 'OC 4500-221 asociada', detail: 'Monto y vigencia calzan', done: true },
          { label: 'Aprobada por el cliente', detail: '2 de octubre', done: true },
          { label: 'Emisión', detail: 'Hoy', done: false },
        ],
      },
      split: {
        title: 'Factura F-1042', meta: 'USD 3.090',
        entities: [
          { name: 'Nimbo AI SpA, Chile', amount: 'USD 1.854', share: '60%' },
          { name: 'Nimbo AI, México', amount: 'USD 1.236', share: '40%' },
        ],
        glosaLabel: 'Glosa',
        glosa: 'Servicio Relvo, octubre 2026. OC 4500-221.',
      },
      collection: {
        title: 'Cobro de F-1042', status: 'Pago parcial',
        paid: 'USD 2.000', of: 'de USD 3.090',
        steps: [
          { label: 'Transferencia conciliada', detail: '18 de octubre', done: true },
          { label: 'Recordatorio por correo', detail: '25 de octubre', done: false },
        ],
      },
    },
    agents: {
      title: 'El trabajo manual que se come tu mes, hecho.',
      soft: 'Tú apruebas solo las excepciones.',
      kpis: [['Tareas hechas hoy', '34'], ['Para revisar', '2']],
      log: [
        { icon: 'doc', text: 'OC 4500-221 leída y asociada', time: '09:02' },
        { icon: 'mail', text: 'HES pedida a Nimbo AI', time: '09:14' },
        { icon: 'channel', text: 'Aviso en #finanzas', time: '09:20' },
        { icon: 'plug', text: 'Consulta vía MCP respondida', time: '09:31' },
      ],
      review: {
        label: 'Requiere revisión',
        title: 'La OC no calza con el contrato.',
        compare: [['OC de Tandem SaaS', 'USD 1.800'], ['Contrato', 'USD 2.100']],
        actions: ['Pedir nueva OC', 'Aprobar igual'],
      },
      principle: 'Los agentes no calculan montos: eso lo hace el motor, siempre igual.',
    },
    intel: {
      title: 'Qué está pasando con tu revenue.',
      soft: 'Lo que ninguna planilla junta.',
      tablist: 'Reportes',
      also: 'Además: facturación, recaudación, cuentas por cobrar y reconocimiento de ingresos bajo IFRS 15.',
      numberLocale: 'es-CL',
      months: ['Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep'],
      tabs: [
        {
          label: 'Qué usan vs. qué pagan',
          kpis: [{ label: 'Consumo sobre el MRR', value: '21%', note: 'Desde 11% en abril.' }],
          chartLabel: 'MRR fijo y consumo por mes, abril a septiembre',
          legend: ['MRR fijo', 'Consumo: llamadas API', 'Consumo: documentos'],
        },
        {
          label: 'Qué tan rápido conviertes trabajo en caja',
          kpis: [
            { label: 'Días en facturar (DTI)', value: '3' },
            { label: 'Días en cobrar (DSO)', value: '38', note: '9 días menos que en abril.' },
          ],
          chartLabel: 'DTI y DSO por mes',
          legend: ['DTI', 'DSO'],
        },
        {
          label: 'Cómo se mueve tu MRR',
          kpis: [{ label: 'MRR de octubre', value: '192,4k', note: '+8.100 neto en el mes.' }],
          chartLabel: 'Movimiento del MRR de septiembre a octubre',
          steps: ['Sep', 'Altas', 'Expansión', 'Consumo', 'Contracción', 'Churn', 'Oct'],
        },
      ],
    },
    products: {
      title: 'Todo tu revenue, en un solo sistema.',
      soft: 'Seis productos, del pricing al reporte.',
      contratos: { desc: 'Cualquier pricing, convertido en reglas exactas.', amount: 'USD 3.140', label: 'total del período', legend: ['Fijo', 'Seats', 'Uso'] },
      medicion: { desc: 'El uso de tus clientes, listo para cobrar.', amount: '1.200 M', label: 'tokens en octubre' },
      aprobaciones: { desc: 'Cada factura sale con su OC aprobada.', steps: ['Pre-factura', 'OC', 'Aprobada', 'Emitida'] },
      cxc: { desc: 'Factura, cobra y concilia en un solo flujo.', amount: 'USD 48.200', label: 'por cobrar', legend: ['Al día', '1 a 30 días', 'Más de 30 días'] },
      agentes: { desc: 'Leen OCs, siguen correos y coordinan al equipo.', amount: '34', label: 'tareas hechas hoy' },
      reporteria: { desc: 'MRR, consumo y DSO sin armar planillas.', amount: 'USD 192,4k', label: 'MRR de octubre', delta: '+4,4%' },
    },
    bridge: {
      title: 'Cobra como vendes.',
      soft: 'Tarjeta o contrato, el mismo motor.',
      plans: {
        title: 'Planes recurrentes',
        body: 'Tus clientes pagan con tarjeta. Relvo mide el consumo, cobra el plan y el uso en automático y te muestra cómo se mueve tu MRR.',
        cta: 'Ver precios',
        link: 'Cómo funciona para planes recurrentes',
      },
      contracts: {
        title: 'Contratos con pricing híbrido',
        body: 'Tus clientes firman contratos. Relvo convierte cada condición en reglas, gestiona las órdenes de compra, factura y cobra.',
        cta: 'Agendar demo',
        link: 'Cómo funciona para contratos',
      },
      usageQuestion: '¿Empezando a cobrar por uso?',
      usageLink: 'Suma consumo sin cambiar de sistema',
    },
    case: {
      title: 'Lo que cambió para nuestros clientes.',
      company: 'TGP',
      about: 'Agencia de prospecting. Cobra un fee fijo más un variable cada mes.',
      big: '70%',
      bigLabel: 'menos tiempo operativo',
      bigSub: 'mientras su operación creció 30% en 3 meses.',
      metricStrong: 'Días en facturar (DTI)',
      metric: ', con aprobaciones de clientes y órdenes de compra incluidas.',
      before: 'Antes',
      after: 'Con Relvo',
      days: 'días',
      quote: 'Hoy trabajamos mucho más rápido, con mayor confianza en los cálculos y con un proceso que puede escalar junto a nuestro crecimiento.',
      author: 'Francesco Cotroneo',
      role: 'Operations Lead, TGP',
    },
    latam: {
      title: 'Hecho para cobrar en LatAm.',
      soft: 'Bancos, medios de pago y facturación de la región.',
      points: [
        'Facturación electrónica en Chile y México',
        'Conciliación con bancos locales',
        'Toku, Fintoc y Stripe',
        'Cualquier moneda, incluida la UF',
        'Varias sociedades, un solo cierre',
        'Órdenes de compra y aprobaciones',
      ],
    },
    integrations: {
      title: 'Se conecta a lo que ya usas.',
      soft: 'Tu CRM, ERP, pagos y banco en un solo motor.',
      label: 'Integraciones',
      names: ['HubSpot', 'Stripe', 'Toku', 'Fintoc', 'Sintropix', 'Slack', 'Google Chat'],
      api: ['¿Usas otro sistema?', 'Conéctalo por API'],
      mcp: ['¿Trabajas con herramientas de IA?', 'Conecta Relvo vía MCP'],
    },

    cta: {
      title: 'Tú vendes. Relvo hace el resto.',
      demo: 'Agendar demo',
      pricing: 'Ver precios',
      docs: 'Ver documentación',
    },
  },
  // EN: las claves nuevas o cambiadas del prototipo quedan marcadas como pendientes (no se traducen
  // todavía). Mientras tanto la home en inglés es una página pendiente: no se publica en producción.
  en: {
    example: 'EXAMPLE',
    hero: {
      eyebrow: 'Revenue Engine for SaaS and AI',
      title: 'Your pricing, turned into revenue. Exact, with no manual work.',
      subtitle: '[PENDIENTE]',
      demo: 'Book a demo',
      how: 'See how it works',
      logos: 'They run their revenue on Relvo',
      stage: {
        window: {
          url: 'app.getrelvo.ai/contratos/nimbo-ai', brand: 'Relvo', nav: ['[PENDIENTE]', '[PENDIENTE]', '[PENDIENTE]', '[PENDIENTE]'],
          label: '[PENDIENTE]', name: 'Nimbo AI', status: '[PENDIENTE]',
          columns: ['[PENDIENTE]', '[PENDIENTE]', '[PENDIENTE]'],
          rows: [['F-1042', 'USD 2,900', '[PENDIENTE]'], ['F-1031', 'USD 2,760', '[PENDIENTE]']],
          paid: '[PENDIENTE]',
        },
        usage: { title: 'Tokens', price: '[PENDIENTE]', amount: '1,200 M', of: '[PENDIENTE]', period: '[PENDIENTE]' },
        invoice: { title: '[PENDIENTE]', meta: '[PENDIENTE]', total: 'USD 2,900', rows: [['[PENDIENTE]', '500'], ['[PENDIENTE]', '2,400']], totalLabel: 'Total' },
        toast: { title: '[PENDIENTE]', meta: '[PENDIENTE]' },
      },
    },
    layers: {
      title: '[PENDIENTE]',
      soft: '[PENDIENTE]',
      numberLocale: 'en-US',
      rails: {
        title: 'Rails',
        sub: 'They calculate the exact amount for every period.',
        plan: 'Growth plan, fixed',
        usage: '[PENDIENTE]',
        detail: '[PENDIENTE]',
        total: 'October total',
      },
      agents: {
        title: 'Agents',
        sub: 'They do the manual work around billing.',
        sender: 'Relvo agent',
        event: 'Purchase order matched.',
        context: 'PO 4500-221 from Nimbo AI matches the contract. The invoice goes out today.',
        running: 'Reading the PO',
        done: 'Done',
      },
      intel: {
        title: 'Intelligence',
        sub: 'It shows how your revenue is moving.',
        label: 'October MRR',
        delta: '+USD 2,900 from Nimbo AI',
      },
    },
    manifesto: {
      label: '[PENDIENTE]',
      lines: ['[PENDIENTE]', '[PENDIENTE]'],
    },
    rails: {
      title: 'The calculation is not up for negotiation.',
      soft: '[PENDIENTE]',
      tablist: '[PENDIENTE]',
      tabs: [{ title: '[PENDIENTE]', desc: '[PENDIENTE]' }, { title: '[PENDIENTE]', desc: '[PENDIENTE]' }, { title: '[PENDIENTE]', desc: '[PENDIENTE]' }, { title: '[PENDIENTE]', desc: '[PENDIENTE]' }],
      pricing: {
        mark: 'N', plan: '[PENDIENTE]', meta: '[PENDIENTE]', price: 'USD 500', per: '[PENDIENTE]',
        seats: ['[PENDIENTE]', '12 × USD 20'],
        tokens: ['Tokens', '1,200 M'],
        tiers: ['[PENDIENTE]', '[PENDIENTE]'],
        discount: ['[PENDIENTE]', '[PENDIENTE]'],
        total: ['[PENDIENTE]', 'USD 3,090'],
      },
      approvals: {
        title: '[PENDIENTE]', meta: 'Nimbo AI',
        steps: [{ label: '[PENDIENTE]', detail: '[PENDIENTE]', done: true }, { label: '[PENDIENTE]', detail: '[PENDIENTE]', done: true }, { label: '[PENDIENTE]', detail: '[PENDIENTE]', done: true }, { label: '[PENDIENTE]', detail: '[PENDIENTE]', done: false }],
      },
      split: {
        title: '[PENDIENTE]', meta: 'USD 3,090',
        entities: [{ name: '[PENDIENTE]', amount: 'USD 1,854', share: '60%' }, { name: '[PENDIENTE]', amount: 'USD 1,236', share: '40%' }],
        glosaLabel: '[PENDIENTE]',
        glosa: '[PENDIENTE]',
      },
      collection: {
        title: '[PENDIENTE]', status: '[PENDIENTE]',
        paid: 'USD 2,000', of: '[PENDIENTE]',
        steps: [{ label: '[PENDIENTE]', detail: '[PENDIENTE]', done: true }, { label: '[PENDIENTE]', detail: '[PENDIENTE]', done: false }],
      },
    },
    agents: {
      title: 'The manual work that eats your month, done.',
      soft: '[PENDIENTE]',
      kpis: [['[PENDIENTE]', '34'], ['[PENDIENTE]', '2']],
      log: [{ icon: 'doc', text: '[PENDIENTE]', time: '09:02' }, { icon: 'mail', text: '[PENDIENTE]', time: '09:14' }, { icon: 'channel', text: '[PENDIENTE]', time: '09:20' }, { icon: 'plug', text: '[PENDIENTE]', time: '09:31' }],
      review: { label: '[PENDIENTE]', title: '[PENDIENTE]', compare: [['[PENDIENTE]', 'USD 1,800'], ['[PENDIENTE]', 'USD 2,100']], actions: ['[PENDIENTE]', '[PENDIENTE]'] },
      principle: '[PENDIENTE]',
    },
    intel: {
      title: 'What is happening with your revenue.',
      soft: '[PENDIENTE]',
      tablist: '[PENDIENTE]',
      also: 'Also: invoicing, collections, accounts receivable and revenue recognition under IFRS 15.',
      numberLocale: 'en-US',
      months: ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'],
      tabs: [
        { label: 'What they use vs. what they pay', kpis: [{ label: '[PENDIENTE]', value: '21%', note: '[PENDIENTE]' }], chartLabel: '[PENDIENTE]', legend: ['[PENDIENTE]', '[PENDIENTE]', '[PENDIENTE]'] },
        { label: 'How fast you turn work into cash', kpis: [{ label: '[PENDIENTE]', value: '3', note: '[PENDIENTE]' }, { label: '[PENDIENTE]', value: '38', note: '[PENDIENTE]' }], chartLabel: '[PENDIENTE]', legend: ['DTI', 'DSO'] },
        { label: 'How your MRR moves', kpis: [{ label: '[PENDIENTE]', value: '192.4k', note: '[PENDIENTE]' }], chartLabel: '[PENDIENTE]', steps: ['Sep', '[PENDIENTE]', '[PENDIENTE]', '[PENDIENTE]', '[PENDIENTE]', 'Churn', 'Oct'] },
      ],
    },
    products: {
      title: '[PENDIENTE]',
      soft: '[PENDIENTE]',
      contratos: { desc: '[PENDIENTE]', amount: 'USD 3,140', label: '[PENDIENTE]', legend: ['[PENDIENTE]', 'Seats', '[PENDIENTE]'] },
      medicion: { desc: '[PENDIENTE]', amount: '1,200 M', label: '[PENDIENTE]' },
      aprobaciones: { desc: '[PENDIENTE]', steps: ['[PENDIENTE]', '[PENDIENTE]', '[PENDIENTE]', '[PENDIENTE]'] },
      cxc: { desc: '[PENDIENTE]', amount: 'USD 48,200', label: '[PENDIENTE]', legend: ['[PENDIENTE]', '[PENDIENTE]', '[PENDIENTE]'] },
      agentes: { desc: '[PENDIENTE]', amount: '34', label: '[PENDIENTE]' },
      reporteria: { desc: '[PENDIENTE]', amount: 'USD 192.4k', label: '[PENDIENTE]', delta: '+4.4%' },
    },
    bridge: {
      title: 'Bill the way you sell.',
      soft: '[PENDIENTE]',
      plans: { title: 'Recurring plans', body: '[PENDIENTE]', cta: '[PENDIENTE]', link: '[PENDIENTE]' },
      contracts: { title: 'Hybrid pricing contracts', body: '[PENDIENTE]', cta: 'Book a demo', link: '[PENDIENTE]' },
      usageQuestion: '[PENDIENTE]',
      usageLink: '[PENDIENTE]',
    },
    case: {
      title: 'What changed for our customers.',
      company: 'TGP',
      about: '[PENDIENTE]',
      big: '70%',
      bigLabel: '[PENDIENTE]',
      bigSub: '[PENDIENTE]',
      metricStrong: '[PENDIENTE]',
      metric: '[PENDIENTE]',
      before: '[PENDIENTE]',
      after: '[PENDIENTE]',
      days: '[PENDIENTE]',
      quote: '[PENDIENTE]',
      author: 'Francesco Cotroneo',
      role: 'Operations Lead, TGP',
    },
    latam: {
      title: 'Built to get paid in LatAm.',
      soft: '[PENDIENTE]',
      points: ['[PENDIENTE]', '[PENDIENTE]', '[PENDIENTE]', '[PENDIENTE]', '[PENDIENTE]', '[PENDIENTE]'],
    },
    integrations: {
      title: 'It connects to what you already use.',
      soft: '[PENDIENTE]',
      label: 'Integrations',
      names: ['HubSpot', 'Stripe', 'Toku', 'Fintoc', 'Sintropix', 'Slack', 'Google Chat'],
      api: ['[PENDIENTE]', '[PENDIENTE]'],
      mcp: ['[PENDIENTE]', '[PENDIENTE]'],
    },

    cta: {
      title: 'You sell. Relvo does the rest.',
      demo: 'Book a demo',
      pricing: '[PENDIENTE]',
      docs: '[PENDIENTE]',
    },
  },
}
